### ISSUE TITLE
A Wire.requestFrom() should not be followed by Wire.endTransmission().

### ISSUE THREAD

**Issue by Koepel** [akuma6099/MCP47FEB#1]
You may remove all the Wire.endTransmission() after a Wire.requestFrom().
Explanation: [Common-mistakes#2](https://github.com/Koepel/How-to-use-the-Arduino-Wire-library/wiki/Common-mistakes#2)

**Comment by akuma6099** [comment]
Updated. Back in the day you had to keep track of your Start/Stop conditions on the bus. I may have been throwing an extra I2C stop just to ensure it was received on the wire. Thanks for the suggestion.
